### ISSUE TITLE
Vereine mit altem Codeformat

### ISSUE THREAD

**Issue by DocFrag** [leichtathletik/ladv-datenformate#13]
Im Meldungs XML 0.7 kommen Vereine noch mit dem alten Codeformat:

`<club id="C1" number="658" type="CLUB" name="ASC Darmstadt" shortname="ASC Darmstadt" country="GER" region="HE"/>`

Hier sollte mMn als Number der Code (Number) wie in den Stammdaten als HE0000658 übermittelt werden, um Konsistent mit allen anderen Systemen zu bleiben.

Sollte, wie im DLV Github erwähnt, es für Vereine in Zukunft auch noch eine GUID geben, sollte diese ebenfalls hier übermittelt werden.

**Comment by mschunk** [comment]
Es ist korrekt, dass sich die " Darstellungsweise" der Vereins ID im Meldungen XML und Stammdaten XML unterschieden. Die Verschiedenen Darstellungen lassen sich eindeutig umwandeln.

Betroffen sind weiterhin:
- Ergebnisse XML - hier werden Vereine wie im Meldungen XML Dargestellt
- Events XML - hier werden Vereine so dargestellt:  `150000003` LAC Erdgas Chemnitz (die 15 ist die numerische LV Kennung)

Desweiteren gilt es ein ähnliches Problem mit :
- Athleten/Startrechte in Meldungen-XML, Ergebnisdaten-XML, Stammdaten-Athleten-XML
- Kreise und Bezirke

Ich denke wir sollten alle IDs (Athleten, Vereine, Kreise, Bezirke) zusammen betrachten und uns auf eine Darstellung einigen und dann alle Datenformate entsprechend anpassen.
