### ISSUE TITLE
Athleten GUID in Meldungen

### ISSUE THREAD

**Issue by DocFrag** [leichtathletik/ladv-datenformate#14]
Um für die Zukunft der deutschen Bestenliste gerüstet zu sein und um Athleten eindeutig mappen zu können, würde ich um Ergänzung der Athleten GUID, aus den Stammdaten, in den Meldungs XML bitten.

**Comment by mschunk** [comment]
Wir werden die Athleten GUID mit in das Meldungs XML als Optionales Datenfeld mit aufnehmen und Dokumentieren das diese sofern vorhanden gesetzt sein soll. Für ausländische Athleten haben wir keine GUIDs, daher muss das Datenfeld Optional sein.

**Comment by mschunk** [comment]
Die Athleten guid wird im Meldungen Format 1.0 aufgenommen. Das DRAFT für die Änderungen am Datenformat sind hier:
leichtathletik/ladv-datenformate#16

**Comment by mschunk** [comment]
Das Meldungen 1.0 Format wird seit April 2021 ausgeliefert.
