### ISSUE TITLE
Ergebnislink im Ergebnis-XML

### ISSUE THREAD

**Issue by diwaffm** [leichtathletik/ladv-datenformate#8]
Da in Zukunft ja von Veranstaltungen aus dem DLV-Verbandgebiet keine Ergebnisse mehr auf ladv veröffentlicht werden dürfen, wäre es sinnvoll, wenn im Ergebnis-XML der Link zur Ergebnisliste auf laportal (bzw. leichtathletik.de) mit übermittelt würde.
Dann hätte der Nutzer von ladv wie bisher auch die Möglichkeit in seinem Workflow auf die Ergebnisse zuzugreifen....

**Comment by mschunk** [comment]
> Da in Zukunft ja von Veranstaltungen aus dem DLV-Verbandgebiet keine Ergebnisse mehr auf ladv veröffentlicht werden dürfen

Diese Aussage ist falsch. LADV wird weiterhin Ergebnisse veröffentlichen.

Ein Link zu Ergebnissen gehört eher in die Metadaten einer Schnittstelle als in das Datenformat für Ergebnisse.

**Comment by mschunk** [comment]
Es ist nicht vorgesehen im Ergebnisdatenformat Links zu Ergebnissen Online aufzunehmen.
